### ISSUE TITLE
 for PowerRanks v1.10.5R2 generated an exception

### ISSUE THREAD

**Issue by servicomcr** [PowerNetworkHub/PowerRanks#61]
[05:18:53] [Server thread/WARN] [nl.svenar.PowerRanks.PowerRanks]: [PowerRanks] Task #2 for PowerRanks v1.10.5R2 generated an exception
 java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.of(Ljava/lang/String;)Lnet/md_5/bungee/api/ChatColor;
        at nl.svenar.PowerRanks.Util.PowerColor.formatHEX(PowerColor.java:75) ~[?:?]
        at nl.svenar.PowerRanks.Util.PowerColor.format(PowerColor.java:53) ~[?:?]
        at nl.svenar.PowerRanks.PowerRanks.chatColor(PowerRanks.java:904) ~[?:?]
        at nl.svenar.PowerRanks.PowerRanks.updateTablistName(PowerRanks.java:894) ~[?:?]
        at nl.svenar.PowerRanks.PowerRanks.updateTablistName(PowerRanks.java:845) ~[?:?]
        at nl.svenar.PowerRanks.Data.TablistManager.updateSorting(TablistManager.java:170) ~[?:?]
        at nl.svenar.PowerRanks.Data.TablistManager$1.run(TablistManager.java:93) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:1.12.2-9a3e486d]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:1.12.2-9a3e486d]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[05:18:53] [Server thread/ERROR] [global]: TIMING_STACK_CORRUPTION - Report this to the plugin PowerRanks(Look for errors above this in the logs) (TimingIdentifier{id=PowerRanks:Task: null (interval:100)} did not stopTiming)
 java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:1.12.2-9a3e486d]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by itzJOHv** [comment]
Server versions below 1.13 are not supported.
