### ISSUE TITLE
Web editor start is throwing an exception

### ISSUE THREAD

**Issue by carlos0202** [PowerNetworkHub/PowerRanks#64]
**I'm not a dummy, so I've checked these**
- [x] I am not using any other permission management plugin
- [x] I use the latest available version of PowerRanks
- [x] I am a human

**Describe the bug**
When using `/pr webeditor start` command, the following exception is thrown:
```
[14:32:44 INFO]: [PR] Preparing web editor...
[14:32:46 WARN]: [PowerRanks] Task #1623 for PowerRanks v1.10.5R2 generated an exception
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
at nl.svenar.common.http.DatabinClient.parseJSON(DatabinClient.java:98) ~[PowerRanks-1.10.5R2.jar:?]
at nl.svenar.common.http.DatabinClient.getResponse(DatabinClient.java:84) ~[PowerRanks-1.10.5R2.jar:?]
at nl.svenar.PowerRanks.Commands.webeditor.cmd_webeditor$1.run(cmd_webeditor.java:128) ~[PowerRanks-1.10.5R2.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-51]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-51]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-51]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-51]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-51]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-51]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-51]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar:?]
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar:?]
at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
... 13 more
[14:32:50 INFO]: [PR] The web editor has timed out! Please try again later.
```

**To Reproduce**
Try starting webeditor interface using the terminal command

**Expected behavior**
The webeditor session should start

 - OS: Windows 10 x64
 - Server type: Paper 1.19
 - Minecraft Version 1.19
 - PowerRanks version PowerRanks-1.10.5R2

**Additional context**

**Comment by svenar-nl** [comment]
This was a server-side issue and should now be resolved!
If not please re-open this issue so more investigation could be done.
